package com.kefang.autoditacte.entity;

import lombok.*;

@Setter
@Getter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CourseWareCourseExerciseCourse extends BaseEntity{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lk_course_warecourse_exercisecourse.id
     *
     * @mbg.generated Sun May 27 20:44:33 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lk_course_warecourse_exercisecourse.course_id
     *
     * @mbg.generated Sun May 27 20:44:33 CST 2018
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lk_course_warecourse_exercisecourse.exercise_course_id
     *
     * @mbg.generated Sun May 27 20:44:33 CST 2018
     */
    private String exerciseCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lk_course_warecourse_exercisecourse.ware_course_id
     *
     * @mbg.generated Sun May 27 20:44:33 CST 2018
     */
    private String wareCourseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lk_course_warecourse_exercisecourse.note
     *
     * @mbg.generated Sun May 27 20:44:33 CST 2018
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lk_course_warecourse_exercisecourse.create_time
     *
     * @mbg.generated Sun May 27 20:44:33 CST 2018
     */
}