spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: testRoot
    password: rootADMIN@)!*
    url: jdbc:mysql://115.239.255.216/kefang_autoditacte?characterEncoding=utf-8&useSSL=false&useAffectedRows=true
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 115.239.255.216
    port: 6379
    password: KEfang123456
server:
  servlet:
    context-path: /autoditacte
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
